from main import process

IMAGE_DIRECTORY = "images"
TARGET_COLOR_RANGE_1 = (90,60,0)
TARGET_COLOR_RANGE_2 = (126,255,255)

process(IMAGE_DIRECTORY, "image1.jpg", TARGET_COLOR_RANGE_1, TARGET_COLOR_RANGE_2)
process(IMAGE_DIRECTORY, "image2.jpg", TARGET_COLOR_RANGE_1, TARGET_COLOR_RANGE_2)
process(IMAGE_DIRECTORY, "image3.jpg", TARGET_COLOR_RANGE_1, TARGET_COLOR_RANGE_2)
process(IMAGE_DIRECTORY, "image4.jpg", TARGET_COLOR_RANGE_1, TARGET_COLOR_RANGE_2)
process(IMAGE_DIRECTORY, "image5.jpg", TARGET_COLOR_RANGE_1, TARGET_COLOR_RANGE_2)
